/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated by scripts/codegen
 * Generated by scripts/codegen
 * Run 'pnpm run codegen' to regenerate.
 */

/**
 * SystemCommands - Commands for the "system" namespace
 */
export interface SystemCommands {
  /**
   * Get system information including platform, versions, and running apps.
   */
  "system/info": {
    args: Record<string, never>;
    response: import("./index").SystemInfo;
  };
}

/**
 * AppbusCommands - Commands for the "appbus" namespace
 */
export interface AppbusCommands {
  /**
   * Register a service that this app exposes
   * Requires "appbus/expose" permission
   */
  "appbus/register": {
    args: {
    serviceName: string;
    description?: string;
    allowedClients?: string[] };
    response: { success: boolean; error?: string };
  };
  /**
   * Unregister a service
   * Requires "appbus/expose" permission
   */
  "appbus/unregister": {
    args: {
    serviceName: string };
    response: { success: boolean };
  };
  /**
   * List all available services
   * No permission required
   */
  "appbus/list": {
    args: Record<string, never>;
    response: { services: import("./index").ServiceInfo[] };
  };
  /**
   * List services by app ID
   * No permission required
   */
  "appbus/list-by-app": {
    args: {
    appId: string };
    response: { services: import("./index").ServiceInfo[] };
  };
  /**
   * Connect to another app's service
   * Creates MessageChannel and transfers ports directly to both apps
   * Requires "appbus/connect" permission
   */
  "appbus/connect": {
    args: {
    targetAppId: string;
    serviceName: string };
    response: import("./index").ConnectResult;
  };
}

/**
 * AppearanceCommands - Commands for the "appearance" namespace
 */
export interface AppearanceCommands {
  "appearance/set-wallpaper": {
    args: {
    wallpaper: import("./index").WallpaperConfig };
    response: void;
  };
  "appearance/get-wallpaper": {
    args: Record<string, never>;
    response: { wallpaper: import("./index").WallpaperPreset };
  };
  "appearance/get-presets": {
    args: Record<string, never>;
    response: {
    solid: import("./index").WallpaperPreset[];
    gradients: import("./index").WallpaperPreset[];
  };
  };
}

/**
 * ContextMenuCommands - Commands for the "context-menu" namespace
 */
export interface ContextMenuCommands {
  "context-menu/register-display": {
    args: { };
    response: { success: boolean };
  };
  "context-menu/open": {
    args: import("./index").ContextMenuOpenArgs & { };
    response: { requestId: string };
  };
  "context-menu/resolve": {
    args: import("./index").ContextMenuResult & { };
    response: { success: boolean };
  };
  "context-menu/close": {
    args: {
    requestId?: string };
    response: { success: boolean };
  };
}

/**
 * DbCommands - Commands for the "db" namespace
 */
export interface DbCommands {
  /**
   * Get a value from database (scoped to caller's app)
   */
  "db/get": {
    args: {
    key: string };
    response: { value: string | undefined };
  };
  /**
   * Set a value in database (scoped to caller's app)
   */
  "db/set": {
    args: {
    key: string;
    value: string };
    response: { success: boolean };
  };
  /**
   * Delete a key from database (scoped to caller's app)
   */
  "db/delete": {
    args: {
    key: string };
    response: { success: boolean };
  };
  /**
   * Check if a key exists (scoped to caller's app)
   */
  "db/has": {
    args: {
    key: string };
    response: { exists: boolean };
  };
  /**
   * Clear all keys (scoped to caller's app)
   */
  "db/clear": {
    args: { };
    response: { success: boolean };
  };
  /**
   * List all keys (scoped to caller's app)
   */
  "db/list": {
    args: { };
    response: { keys: string[] };
  };
  /**
   * Get a value from any app's namespace (superuser only)
   */
  "db/get/su": {
    args: {
    appId: string;
    key: string };
    response: { value: string | undefined };
  };
  /**
   * Set a value in any app's namespace (superuser only)
   */
  "db/set/su": {
    args: {
    appId: string;
    key: string;
    value: string };
    response: { success: boolean };
  };
  /**
   * Delete a key from any app's namespace (superuser only)
   */
  "db/delete/su": {
    args: {
    appId: string;
    key: string };
    response: { success: boolean };
  };
  /**
   * Check if a key exists in any app's namespace (superuser only)
   */
  "db/has/su": {
    args: {
    appId: string;
    key: string };
    response: { exists: boolean };
  };
  /**
   * Clear all keys in any app's namespace (superuser only)
   */
  "db/clear/su": {
    args: {
    appId: string };
    response: { success: boolean };
  };
  /**
   * List all keys in any app's namespace (superuser only)
   */
  "db/list/su": {
    args: {
    appId: string };
    response: { keys: string[] };
  };
}

/**
 * FileCommands - Commands for the "file" namespace
 */
export interface FileCommands {
  /**
   * Open a file with its default handler
   */
  "file/open": {
    args: { path: string };
    response: import("./index").FileOpenResult;
  };
  /**
   * Open a file with a specific app
   */
  "file/open-with": {
    args: {
    path: string;
    appId: string };
    response: import("./index").FileOpenResult;
  };
  /**
   * Get the default handler app for a file extension
   */
  "file/get-handler": {
    args: {
    extension: string };
    response: { appId: string | undefined };
  };
  /**
   * Set user preference for a file extension's default handler
   */
  "file/set-default-handler": {
    args: {
    extension: string;
    appId: string };
    response: void;
  };
  /**
   * Remove user preference for a file extension (revert to default)
   */
  "file/remove-default-handler": {
    args: { extension: string };
    response: void;
  };
  /**
   * Get all apps that can handle a specific file extension
   */
  "file/get-supported-handlers": {
    args: {
    extension: string };
    response: import("./index").FileHandlerInfo[];
  };
  /**
   * Get all file type associations
   */
  "file/get-associations": {
    args: Record<string, never>;
    response: Record<
      string,
      { default: string | undefined; userOverride: string | undefined }
    >;
  };
}

/**
 * FsCommands - Commands for the "fs" namespace
 */
export interface FsCommands {
  /**
   * Read the contents of a file.
   */
  "fs/read": {
    args: {
    path: string;
    encoding?: string };
    response: string;
  };
  /**
   * Write content to a file, creating directories if needed.
   */
  "fs/write": {
    args: {
    path: string;
    content: string;
    encoding?: string };
    response: void;
  };
  /**
   * Check if a file or directory exists.
   */
  "fs/exists": {
    args: { path: string };
    response: boolean;
  };
  /**
   * Create a directory and any necessary parent directories.
   */
  "fs/mkdir": {
    args: { path: string };
    response: void;
  };
  /**
   * List contents of a directory.
   */
  "fs/readdir": {
    args: { path: string };
    response: string[];
  };
  /**
   * Get file or directory statistics.
   */
  "fs/stat": {
    args: { path: string };
    response: import("./index").FileStats;
  };
  /**
   * Search for files and directories using glob patterns.
   */
  "fs/search": {
    args: {
    path: string;
    pattern: string;
    limit?: number };
    response: import("./index").SearchResult[];
  };
  /**
   * Delete a file or directory.
   * For directories, removes recursively.
   */
  "fs/delete": {
    args: { path: string };
    response: void;
  };
}

/**
 * I18nCommands - Commands for the "i18n" namespace
 */
export interface I18nCommands {
  "i18n/get-locale": {
    args: Record<string, never>;
    response: { locale: string };
  };
  "i18n/get-common": {
    args: { locale: string };
    response: {
    translations: Record<string, any>;
  };
  };
}

/**
 * EventCommands - Commands for the "event" namespace
 */
export interface EventCommands {
  "event/subscribe": {
    args: {
    eventName: string };
    response: void;
  };
  "event/unsubscribe": {
    args: {
    eventName: string };
    response: void;
  };
  "event/exists": {
    args: { eventName: string };
    response: boolean;
  };
}

/**
 * NotificationCommands - Commands for the "notification" namespace
 */
export interface NotificationCommands {
  /**
   * Push a new notification to subscribers.
   */
  "notification/push": {
    args: {
    title: string;
    message: string;
    timeout?: number;
    type?: import("./index").NotificationType };
    response: import("./index").Notification;
  };
}

/**
 * PackageCommands - Commands for the "package" namespace
 */
export interface PackageCommands {
  /**
   * Install an application from a local path.
   */
  "package/install": {
    args: {
    sourcePath: string };
    response: import("./index").RuntimeAppManifest;
  };
  /**
   * Uninstall an application by its ID.
   */
  "package/uninstall": {
    args: { appId: string };
    response: boolean;
  };
  /**
   * List all installed applications.
   * @param showHidden - If true, includes overlay apps and daemons (hidden by default)
   * @param showRestricted - If true, includes apps the current user cannot launch (hidden by default)
   */
  "package/list": {
    args: {
    showHidden?: boolean;
    showRestricted?: boolean };
    response: import("./index").RuntimeAppManifest[];
  };
  /**
   * Toggle hot reload for an app
   */
  "package/toggle-hot-reload": {
    args: {
    appId: string };
    response: { enabled: boolean };
  };
  /**
   * Check if hot reload is enabled for an app
   */
  "package/is-hot-reload-enabled": {
    args: {
    appId: string };
    response: { enabled: boolean };
  };
  /**
   * Get the icon for an installed application as a data URL.
   */
  "package/get-icon": {
    args: {
    appId: string };
    response: { icon: string | undefined };
  };
  /**
   * Get info about a package file without installing it
   */
  "package/get-info": {
    args: {
    path: string };
    response: { success: boolean; manifest?: import("./index").AppManifest; error?: string };
  };
  /**
   * Get the installed size of an app in bytes
   */
  "package/get-size": {
    args: {
    appId: string };
    response: { size: number | undefined };
  };
}

/**
 * ProcessCommands - Commands for the "process" namespace
 */
export interface ProcessCommands {
  /**
   * Launch an application instance.
   */
  "process/launch": {
    args: {
    appId: string;
    bounds?: import("./index").ViewBounds };
    response: import("./index").LaunchResult;
  };
  /**
   * Stop a running application instance.
   */
  "process/stop": {
    args: { appId: string };
    response: { success: boolean };
  };
  /**
   * List all running application processes.
   * @param showHidden - If true, includes overlay apps (hidden by default)
   */
  "process/list": {
    args: { showHidden?: boolean };
    response: import("./index").AppInstance[];
  };
}

/**
 * SettingsCommands - Commands for the "settings" namespace
 */
export interface SettingsCommands {
  /**
   * Get a setting value (scoped to caller's app)
   */
  "settings/get": {
    args: {
    key: string };
    response: { value: string | undefined };
  };
  /**
   * Set a setting value (scoped to caller's app)
   */
  "settings/set": {
    args: {
    key: string;
    value: string };
    response: { success: boolean };
  };
  /**
   * List all settings keys (scoped to caller's app)
   */
  "settings/list": {
    args: { };
    response: { keys: string[] };
  };
  /**
   * Get all settings with values (scoped to caller's app)
   */
  "settings/get-all": {
    args: { };
    response: { settings: Record<string, string> };
  };
  /**
   * Reset a setting to default (scoped to caller's app)
   */
  "settings/reset": {
    args: {
    key: string;
    schema?: import("./index").SettingsCategory[] };
    response: { success: boolean };
  };
  /**
   * Get a setting from any app's namespace (superuser only)
   */
  "settings/get/su": {
    args: {
    appId: string;
    key: string };
    response: { value: string | undefined };
  };
  /**
   * Set a setting in any app's namespace (superuser only)
   */
  "settings/set/su": {
    args: {
    appId: string;
    key: string;
    value: string };
    response: { success: boolean };
  };
  /**
   * List all settings in any app's namespace (superuser only)
   * @param showRestricted - If true, includes settings the current user cannot access (hidden by default)
   */
  "settings/list/su": {
    args: {
    appId: string;
    showRestricted?: boolean };
    response: { keys: string[] };
  };
  /**
   * Get all settings with values for any app (superuser only)
   * @param showRestricted - If true, includes settings the current user cannot access (hidden by default)
   */
  "settings/get-all/su": {
    args: {
    appId: string;
    showRestricted?: boolean };
    response: { settings: Record<string, string> };
  };
  /**
   * Reset a setting for any app (superuser only)
   */
  "settings/reset/su": {
    args: {
    appId: string;
    key: string;
    schema?: import("./index").SettingsCategory[] };
    response: { success: boolean };
  };
  /**
   * Get the Eden settings schema
   * @param showRestricted - If true, includes settings the current user cannot access (hidden by default)
   */
  "settings/schema": {
    args: {
    showRestricted?: boolean };
    response: { schema: import("./index").SettingsCategory[] };
  };
}

/**
 * UserCommands - Commands for the "user" namespace
 */
export interface UserCommands {
  /**
   * List all users.
   */
  "user/list": {
    args: Record<string, never>;
    response: { users: import("./index").UserProfile[] };
  };
  /**
   * Return the current logged-in user.
   */
  "user/get-current": {
    args: Record<string, never>;
    response: { user: import("./index").UserProfile | null };
  };
  /**
   * Authenticate a user and establish a session.
   */
  "user/login": {
    args: {
    username: string;
    password: string };
    response: { success: boolean; user?: import("./index").UserProfile; error?: string };
  };
  /**
   * End the current session.
   */
  "user/logout": {
    args: Record<string, never>;
    response: { success: boolean };
  };
  /**
   * Create a new user.
   */
  "user/create": {
    args: {
    username?: string;
    name: string;
    role?: import("./index").UserRole;
    password: string;
    grants?: string[] };
    response: { user: import("./index").UserProfile };
  };
  /**
   * Update user profile details or grants.
   */
  "user/update": {
    args: {
    username: string;
    name?: string;
    role?: import("./index").UserRole;
    grants?: string[] };
    response: { user: import("./index").UserProfile };
  };
  /**
   * Delete a user.
   */
  "user/delete": {
    args: {
    username: string };
    response: { success: boolean };
  };
  /**
   * Set a user's password.
   */
  "user/set-password": {
    args: {
    username: string;
    password: string };
    response: { success: boolean };
  };
  /**
   * Change the current user's password.
   */
  "user/change-password": {
    args: {
    currentPassword: string;
    newPassword: string };
    response: { success: boolean; error?: string };
  };
  /**
   * Check whether the current user has a specific grant.
   */
  "user/has-grant": {
    args: { grant: string };
    response: { allowed: boolean };
  };
  /**
   * Return the configured default username.
   */
  "user/get-default": {
    args: Record<string, never>;
    response: { username: string | null };
  };
  /**
   * Update the configured default username.
   */
  "user/set-default": {
    args: {
    username: string | null };
    response: { success: boolean };
  };
}

/**
 * ViewCommands - Commands for the "view" namespace
 */
export interface ViewCommands {
  /**
   * Update the bounds (position and size) of a specific view.
   */
  "view/update-view-bounds": {
    args: {
    appId: string;
    bounds: import("./index").ViewBounds };
    response: { success: boolean };
  };
  /**
   * Show or hide a specific view.
   */
  "view/set-view-visibility": {
    args: {
    appId: string;
    visible: boolean };
    response: { success: boolean };
  };
  /**
   * Bring an application's view to the front and focus it.
   */
  "view/focus-app": {
    args: { appId: string };
    response: { success: boolean };
  };
  /**
   * Update the available workspace bounds (e.g. after taskbar resize).
   */
  "view/update-global-bounds": {
    args: {
    bounds: import("./index").ViewBounds;
    windowSize: import("./index").WindowSize };
    response: { success: boolean };
  };
  /**
   * Toggle between floating and tiled window modes.
   */
  "view/toggle-view-mode": {
    args: {
    appId: string;
    mode?: "floating" | "tiled" };
    response: { success: boolean };
  };
  /**
   * Start dragging a window.
   */
  "view/start-drag": {
    args: {
    appId: string;
    startX: number;
    startY: number };
    response: { success: boolean };
  };
  /**
   * End the current drag operation.
   */
  "view/end-drag": {
    args: { appId: string };
    response: { success: boolean };
  };
  /**
   * Handle global mouse up event to stop any active drag/resize operations.
   */
  "view/global-mouseup": {
    args: Record<string, never>;
    response: { success: boolean };
  };
  /**
   * Start resizing a window.
   */
  "view/start-resize": {
    args: {
    appId: string;
    startX: number;
    startY: number };
    response: { success: boolean };
  };
  /**
   * End the current resize operation.
   */
  "view/end-resize": {
    args: {
    appId: string };
    response: { success: boolean };
  };
  /**
   * Get the current dimensions of the main window.
   */
  "view/window-size": {
    args: Record<string, never>;
    response: import("./index").WindowSize;
  };
}

/**
 * Global command map - merge all command namespaces
 */
export interface CommandMap extends SystemCommands, AppbusCommands, AppearanceCommands, ContextMenuCommands, DbCommands, FileCommands, FsCommands, I18nCommands, EventCommands, NotificationCommands, PackageCommands, ProcessCommands, SettingsCommands, UserCommands, ViewCommands {}
