/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated by scripts/codegen
 * Generated by scripts/codegen
 * Run 'pnpm run codegen' to regenerate.
 */

/**
 * SystemCommands - Commands for the "system" namespace
 */
export interface SystemCommands {
  /**
   * Get system information including platform, versions, and running apps.
   */
  "system/info": {
    mode: "immediate";
    args: Record<string, never>;
    response: import("./index").SystemInfo;
  };
  /**
   * Get consumer-controlled product branding for SDK-owned interfaces.
   */
  "system/branding": {
    mode: "immediate";
    args: Record<string, never>;
    response: import("./index").EdenBrandingInfo;
  };
  "system/power-capabilities": {
    mode: "immediate";
    args: Record<string, never>;
    response: import("./index").EdenPowerCapabilities;
  };
  "system/power": {
    mode: "operation";
    args: { action: "poweroff" | "reboot" };
    response: import("./index").OperationHandle<"system/power">;
    completion: void;
  };
}

/**
 * AssociationsCommands - Commands for the "associations" namespace
 */
export interface AssociationsCommands {
  "associations/get": {
    mode: "immediate";
    args: { key: string };
    response: {
    association: import("./index").AppAssociation | undefined;
  };
  };
  "associations/set": {
    mode: "immediate";
    args: {
    key: string;
    appId: string;
    kind: string;
    label?: string };
    response: { success: boolean };
  };
  "associations/remove": {
    mode: "immediate";
    args: { key: string };
    response: { success: boolean };
  };
  "associations/list": {
    mode: "immediate";
    args: { kindPrefix?: string };
    response: {
    associations: Record<string, import("./index").AppAssociation>;
  };
  };
}

/**
 * AppbusCommands - Commands for the "appbus" namespace
 */
export interface AppbusCommands {
  /**
   * Register a service that this app exposes
   * Requires "appbus/expose" permission
   */
  "appbus/register": {
    mode: "immediate";
    args: {
    serviceName: string;
    description?: string;
    allowedClients?: string[] };
    response: { success: boolean; error?: string };
  };
  /**
   * Unregister a service
   * Requires "appbus/expose" permission
   */
  "appbus/unregister": {
    mode: "immediate";
    args: {
    serviceName: string };
    response: { success: boolean };
  };
  /**
   * List all available services
   * No permission required
   */
  "appbus/list": {
    mode: "immediate";
    args: Record<string, never>;
    response: { services: import("./index").ServiceInfo[] };
  };
  /**
   * List services by app ID
   * No permission required
   */
  "appbus/list-by-app": {
    mode: "immediate";
    args: {
    appId: string };
    response: { services: import("./index").ServiceInfo[] };
  };
  /**
   * Connect to another app's service
   * Creates MessageChannel and transfers ports directly to both apps
   * Requires "appbus/connect" permission
   */
  "appbus/connect": {
    mode: "immediate";
    args: {
    targetAppId: string;
    serviceName: string };
    response: import("./index").ConnectResult;
  };
}

/**
 * AppearanceCommands - Commands for the "appearance" namespace
 */
export interface AppearanceCommands {
  "appearance/set-wallpaper": {
    mode: "immediate";
    args: {
    wallpaper: import("./index").WallpaperConfig };
    response: void;
  };
  "appearance/get-wallpaper": {
    mode: "immediate";
    args: Record<string, never>;
    response: { wallpaper: import("./index").WallpaperPreset };
  };
  "appearance/get-presets": {
    mode: "immediate";
    args: Record<string, never>;
    response: {
    solid: import("./index").WallpaperPreset[];
    gradients: import("./index").WallpaperPreset[];
  };
  };
}

/**
 * ContextMenuCommands - Commands for the "context-menu" namespace
 */
export interface ContextMenuCommands {
  "context-menu/register-display": {
    mode: "immediate";
    args: { };
    response: { success: boolean };
  };
  "context-menu/open": {
    mode: "immediate";
    args: import("./index").ContextMenuOpenArgs & { };
    response: { requestId: string };
  };
  "context-menu/resolve": {
    mode: "immediate";
    args: import("./index").ContextMenuResult & { };
    response: { success: boolean };
  };
  "context-menu/close": {
    mode: "immediate";
    args: {
    requestId?: string };
    response: { success: boolean };
  };
}

/**
 * DaemonCommands - Commands for the "daemon" namespace
 */
export interface DaemonCommands {
  "daemon/list": {
    mode: "immediate";
    args: Record<string, never>;
    response: import("./index").DaemonStatus[];
  };
  "daemon/update-definition": {
    mode: "immediate";
    args: {
    definition: import("./index").DaemonDefinition };
    response: { success: true };
  };
  "daemon/enable": {
    mode: "immediate";
    args: { appId: string };
    response: { success: true };
  };
  "daemon/disable": {
    mode: "immediate";
    args: { appId: string };
    response: { success: true };
  };
  "daemon/start": {
    mode: "operation";
    args: { appId: string };
    response: import("./index").OperationHandle<"daemon/start">;
    completion: { success: true };
  };
  "daemon/stop": {
    mode: "operation";
    args: { appId: string };
    response: import("./index").OperationHandle<"daemon/stop">;
    completion: { success: true };
  };
  "daemon/restart": {
    mode: "operation";
    args: { appId: string };
    response: import("./index").OperationHandle<"daemon/restart">;
    completion: { success: true };
  };
}

/**
 * DbCommands - Commands for the "db" namespace
 */
export interface DbCommands {
  /**
   * Get a value from database (scoped to caller's app)
   */
  "db/get": {
    mode: "immediate";
    args: {
    key: string };
    response: { value: string | undefined };
  };
  /**
   * Set a value in database (scoped to caller's app)
   */
  "db/set": {
    mode: "immediate";
    args: {
    key: string;
    value: string };
    response: { success: boolean };
  };
  /**
   * Delete a key from database (scoped to caller's app)
   */
  "db/delete": {
    mode: "immediate";
    args: {
    key: string };
    response: { success: boolean };
  };
  /**
   * Check if a key exists (scoped to caller's app)
   */
  "db/has": {
    mode: "immediate";
    args: {
    key: string };
    response: { exists: boolean };
  };
  /**
   * Clear all keys (scoped to caller's app)
   */
  "db/clear": {
    mode: "immediate";
    args: { };
    response: { success: boolean };
  };
  /**
   * List all keys (scoped to caller's app)
   */
  "db/list": {
    mode: "immediate";
    args: { };
    response: { keys: string[] };
  };
  /**
   * Get a value from any app's namespace (superuser only)
   */
  "db/get/su": {
    mode: "immediate";
    args: {
    appId: string;
    key: string };
    response: { value: string | undefined };
  };
  /**
   * Set a value in any app's namespace (superuser only)
   */
  "db/set/su": {
    mode: "immediate";
    args: {
    appId: string;
    key: string;
    value: string };
    response: { success: boolean };
  };
  /**
   * Delete a key from any app's namespace (superuser only)
   */
  "db/delete/su": {
    mode: "immediate";
    args: {
    appId: string;
    key: string };
    response: { success: boolean };
  };
  /**
   * Check if a key exists in any app's namespace (superuser only)
   */
  "db/has/su": {
    mode: "immediate";
    args: {
    appId: string;
    key: string };
    response: { exists: boolean };
  };
  /**
   * Clear all keys in any app's namespace (superuser only)
   */
  "db/clear/su": {
    mode: "immediate";
    args: {
    appId: string };
    response: { success: boolean };
  };
  /**
   * List all keys in any app's namespace (superuser only)
   */
  "db/list/su": {
    mode: "immediate";
    args: {
    appId: string };
    response: { keys: string[] };
  };
}

/**
 * FileCommands - Commands for the "file" namespace
 */
export interface FileCommands {
  /**
   * Open a file with its default handler
   */
  "file/open": {
    mode: "operation";
    args: {
    location: import("./index").FilesystemLocation };
    response: import("./index").OperationHandle<"file/open">;
    completion: import("./index").FileOpenResult;
  };
  /**
   * Open a file with a specific app
   */
  "file/open-with": {
    mode: "operation";
    args: {
    location: import("./index").FilesystemLocation;
    appId: string };
    response: import("./index").OperationHandle<"file/open-with">;
    completion: import("./index").FileOpenResult;
  };
  /**
   * Get the default handler app for a file path
   */
  "file/get-handler": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation };
    response: { appId: string | undefined };
  };
  /**
   * Set user preference for a file path's default handler
   */
  "file/set-default-handler": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation;
    appId: string };
    response: void;
  };
  /**
   * Remove user preference for a file path (revert to default)
   */
  "file/remove-default-handler": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation };
    response: void;
  };
  /**
   * Get all apps that can handle a specific file path
   */
  "file/get-supported-handlers": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation };
    response: import("./index").FileHandlerInfo[];
  };
  /**
   * Get all file type associations
   */
  "file/get-associations": {
    mode: "immediate";
    args: Record<string, never>;
    response: Record<
      string,
      { default: string | undefined; userOverride: string | undefined }
    >;
  };
}

/**
 * FilePickerCommands - Commands for the "file-picker" namespace
 */
export interface FilePickerCommands {
  "file-picker/register-display": {
    mode: "immediate";
    args: { };
    response: { success: boolean };
  };
  "file-picker/open": {
    mode: "immediate";
    args: import("./index").FilePickerOpenArgs & { };
    response: { requestId: string };
  };
  "file-picker/resolve": {
    mode: "immediate";
    args: import("./index").FilePickerResult & { };
    response: { success: boolean };
  };
  "file-picker/close": {
    mode: "immediate";
    args: {
    requestId?: string };
    response: { success: boolean };
  };
}

/**
 * FsCommands - Commands for the "fs" namespace
 */
export interface FsCommands {
  "fs/volumes": {
    mode: "immediate";
    args: Record<string, never>;
    response: import("./index").FilesystemVolume[];
  };
  /**
   * Safely eject a device after draining admitted volume I/O.
   */
  "fs/eject": {
    mode: "operation";
    args: { volume: string };
    response: import("./index").OperationHandle<"fs/eject">;
    completion: void;
  };
  /**
   * Read the contents of a file.
   */
  "fs/read": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation;
    encoding?: string };
    response: string;
  };
  /**
   * Read the raw contents of a file.
   */
  "fs/read-binary": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation };
    response: Uint8Array;
  };
  /**
   * Write content to a file, creating directories if needed.
   */
  "fs/write": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation;
    content: string;
    encoding?: string };
    response: void;
  };
  /**
   * Write raw bytes to a file, creating directories if needed.
   */
  "fs/write-binary": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation;
    content: Uint8Array };
    response: void;
  };
  /**
   * Check if a file or directory exists.
   */
  "fs/exists": {
    mode: "immediate";
    args: { location: import("./index").FilesystemLocation };
    response: boolean;
  };
  /**
   * Create a directory and any necessary parent directories.
   */
  "fs/mkdir": {
    mode: "immediate";
    args: { location: import("./index").FilesystemLocation };
    response: void;
  };
  /**
   * List contents of a directory.
   */
  "fs/readdir": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation };
    response: string[];
  };
  /**
   * Get file or directory statistics.
   */
  "fs/stat": {
    mode: "immediate";
    args: { location: import("./index").FilesystemLocation };
    response: import("./index").FileStats;
  };
  "fs/watch": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation };
    response: { watchId: string };
  };
  "fs/unwatch": {
    mode: "immediate";
    args: {
    watchId: string };
    response: void;
  };
  /**
   * Resolve an Eden path to the underlying OS path.
   */
  "fs/resolve": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation };
    response: { realPath: string };
  };
  /**
   * Search for files and directories using glob patterns.
   */
  "fs/search": {
    mode: "immediate";
    args: {
    location: import("./index").FilesystemLocation;
    pattern: string;
    limit?: number };
    response: import("./index").SearchResult[];
  };
  /**
   * Delete a file or directory.
   * For directories, removes recursively.
   */
  "fs/delete": {
    mode: "operation";
    args: { location: import("./index").FilesystemLocation };
    response: import("./index").OperationHandle<"fs/delete">;
    completion: void;
  };
  /**
   * Copy a file or directory.
   * Directories are copied recursively.
   * Existing destinations are replaced only when overwrite is true.
   */
  "fs/cp": {
    mode: "operation";
    args: import("./index").FilesystemTransferArgs;
    response: import("./index").OperationHandle<"fs/cp">;
    completion: void;
  };
  /**
   * Move or rename a file or directory.
   * Existing destinations are replaced only when overwrite is true.
   */
  "fs/mv": {
    mode: "operation";
    args: import("./index").FilesystemTransferArgs;
    response: import("./index").OperationHandle<"fs/mv">;
    completion: void;
  };
}

/**
 * I18nCommands - Commands for the "i18n" namespace
 */
export interface I18nCommands {
  "i18n/get-locale": {
    mode: "immediate";
    args: Record<string, never>;
    response: { locale: string };
  };
  "i18n/get-common": {
    mode: "immediate";
    args: { locale: string };
    response: {
    translations: import("./index").RecursiveObject<string>;
  };
  };
}

/**
 * EventCommands - Commands for the "event" namespace
 */
export interface EventCommands {
  "event/subscribe": {
    mode: "immediate";
    args: {
    eventName: string;
    operation?: import("./index").OperationObservation };
    response: void;
  };
  "event/unsubscribe": {
    mode: "immediate";
    args: {
    eventName: string;
    operation?: import("./index").OperationObservation };
    response: void;
  };
  "event/exists": {
    mode: "immediate";
    args: { eventName: string };
    response: boolean;
  };
}

/**
 * NotificationCommands - Commands for the "notification" namespace
 */
export interface NotificationCommands {
  /**
   * Register the notification display provider.
   */
  "notification/register-display": {
    mode: "immediate";
    args: { };
    response: { success: boolean };
  };
  /**
   * Push a new notification to subscribers.
   */
  "notification/push": {
    mode: "immediate";
    args: {
    title: string;
    message: string;
    timeout?: number;
    type?: import("./index").NotificationType;
    actions?: import("./index").NotificationAction[] };
    response: import("./index").Notification;
  };
  /**
   * Report a notification action click from the toaster.
   */
  "notification/action-clicked": {
    mode: "immediate";
    args: {
    notificationId: string;
    actionId: string };
    response: { success: boolean };
  };
  /**
   * Report a notification dismissal from the toaster.
   */
  "notification/dismissed": {
    mode: "immediate";
    args: {
    notificationId: string };
    response: { success: boolean };
  };
}

/**
 * OperationCommands - Commands for the "operation" namespace
 */
export interface OperationCommands {
  "operation/get": {
    mode: "immediate";
    args: { handle: import("./index").OperationHandle };
    response: import("./index").OperationSnapshot;
  };
  "operation/cancel": {
    mode: "immediate";
    args: { handle: import("./index").OperationHandle };
    response: void;
  };
  "operation/list": {
    mode: "immediate";
    args: Record<string, never>;
    response: import("./index").OperationSnapshot[];
  };
}

/**
 * PackageCommands - Commands for the "package" namespace
 */
export interface PackageCommands {
  /**
   * Install an application or DLC from a local path.
   */
  "package/install": {
    mode: "operation";
    args: {
    source: import("./index").FilesystemLocation;
    replace?: boolean };
    response: import("./index").OperationHandle<"package/install">;
    completion: import("./index").InstalledPackageManifest;
  };
  /**
   * Uninstall an application or DLC by its package ID.
   */
  "package/uninstall": {
    mode: "operation";
    args: { packageId: string };
    response: import("./index").OperationHandle<"package/uninstall">;
    completion: boolean;
  };
  /**
   * List all installed applications.
   * @param showHidden - If true, includes overlay apps and daemons (hidden by default)
   * @param showRestricted - If true, includes apps the current user cannot launch (hidden by default)
   */
  "package/list": {
    mode: "immediate";
    args: {
    showHidden?: boolean;
    showRestricted?: boolean };
    response: import("./index").RuntimeAppManifest[];
  };
  /**
   * Identify the authenticated app and return its extension resources.
   */
  "package/self": {
    mode: "immediate";
    args: { };
    response: import("./index").InstalledPackageInfo;
  };
  /**
   * Get an installed package and any extension resources it owns.
   */
  "package/get": {
    mode: "immediate";
    args: {
    packageId: string };
    response: import("./index").InstalledPackageInfo;
  };
  /**
   * Toggle hot reload for an app
   */
  "package/toggle-hot-reload": {
    mode: "immediate";
    args: {
    packageId: string };
    response: { enabled: boolean };
  };
  /**
   * Check if hot reload is enabled for an app
   */
  "package/is-hot-reload-enabled": {
    mode: "immediate";
    args: {
    packageId: string };
    response: { enabled: boolean };
  };
  /**
   * Get the icon for an installed package as a data URL.
   */
  "package/get-icon": {
    mode: "immediate";
    args: {
    packageId: string };
    response: { icon: string | undefined };
  };
  /**
   * Get info about a package file without installing it
   */
  "package/get-info": {
    mode: "immediate";
    args: { location: import("./index").FilesystemLocation };
    response: {
    success: boolean;
    manifest?: import("./index").PackageManifest;
    preview?: import("./index").PackageOperationPreview;
    error?: string;
  };
  };
  /**
   * Get the installed size of a package in bytes.
   */
  "package/get-size": {
    mode: "immediate";
    args: {
    packageId: string };
    response: { size: number | undefined };
  };
}

/**
 * ProcessCommands - Commands for the "process" namespace
 */
export interface ProcessCommands {
  /**
   * Launch an application instance.
   * Requires "process/manage" permission.
   */
  "process/launch": {
    mode: "operation";
    args: {
    appId: string;
    bounds?: import("./index").ViewBounds };
    response: import("./index").OperationHandle<"process/launch">;
    completion: import("./index").LaunchResult;
  };
  /**
   * Stop a running application instance.
   * Requires "process/manage" permission.
   */
  "process/stop": {
    mode: "operation";
    args: { appId: string };
    response: import("./index").OperationHandle<"process/stop">;
    completion: { success: boolean };
  };
  /**
   * Stop the caller app instance.
   * No explicit permission required - this endpoint only allows self-exit.
   */
  "process/exit": {
    mode: "operation";
    args: { };
    response: import("./index").OperationHandle<"process/exit">;
    completion: { success: boolean };
  };
  /**
   * List all running application processes.
   * Requires "process/read" permission.
   * @param showHidden - If true, includes overlay apps (hidden by default)
   */
  "process/list": {
    mode: "immediate";
    args: { showHidden?: boolean };
    response: import("./index").AppInstance[];
  };
  /**
   * Return CPU and memory metrics for running Eden apps.
   * Requires "process/read" permission.
   * @param showHidden - If true, includes overlay apps and backend-only apps
   * @param pollingTimeoutMs - How long main should keep the shared sampler alive
   * @param waitForAccurateCpu - If false, returns the current sample immediately,
   * even before Electron has a full CPU interval
   */
  "process/metrics": {
    mode: "immediate";
    args: {
    showHidden?: boolean;
    pollingTimeoutMs?: number;
    waitForAccurateCpu?: boolean };
    response: import("./index").ProcessMetricsSnapshot;
  };
}

/**
 * SessionCommands - Commands for the "session" namespace
 */
export interface SessionCommands {
  "session/get-current": {
    mode: "immediate";
    args: Record<string, never>;
    response: { user: import("./index").UserProfile | null };
  };
  "session/login": {
    mode: "operation";
    args: {
    username: string;
    password: string };
    response: import("./index").OperationHandle<"session/login">;
    completion: { success: boolean; user?: import("./index").UserProfile; error?: string };
  };
  "session/logout": {
    mode: "operation";
    args: Record<string, never>;
    response: import("./index").OperationHandle<"session/logout">;
    completion: { success: boolean };
  };
}

/**
 * SettingsCommands - Commands for the "settings" namespace
 */
export interface SettingsCommands {
  /**
   * Get a setting value (scoped to caller's app)
   */
  "settings/get": {
    mode: "immediate";
    args: {
    key: string;
    appId?: string };
    response: { value: string | undefined };
  };
  /**
   * Set a setting value (scoped to caller's app)
   */
  "settings/set": {
    mode: "immediate";
    args: {
    key: string;
    value: string };
    response: { success: boolean };
  };
  /**
   * List all settings keys (scoped to caller's app)
   */
  "settings/list": {
    mode: "immediate";
    args: { };
    response: { keys: string[] };
  };
  /**
   * Get all settings with values (scoped to caller's app)
   */
  "settings/get-all": {
    mode: "immediate";
    args: { };
    response: { settings: Record<string, string> };
  };
  /**
   * Reset a setting to default (scoped to caller's app)
   */
  "settings/reset": {
    mode: "immediate";
    args: {
    key: string;
    schema?: import("./index").SettingsCategory[] };
    response: { success: boolean };
  };
  /**
   * Get a setting from any app's namespace (superuser only)
   */
  "settings/get/su": {
    mode: "immediate";
    args: {
    appId: string;
    key: string };
    response: { value: string | undefined };
  };
  /**
   * Set a setting in any app's namespace (superuser only)
   */
  "settings/set/su": {
    mode: "immediate";
    args: {
    appId: string;
    key: string;
    value: string };
    response: { success: boolean };
  };
  /**
   * List all settings in any app's namespace (superuser only)
   * @param showRestricted - If true, includes settings the current user cannot access (hidden by default)
   */
  "settings/list/su": {
    mode: "immediate";
    args: {
    appId: string;
    showRestricted?: boolean };
    response: { keys: string[] };
  };
  /**
   * Get all settings with values for any app (superuser only)
   * @param showRestricted - If true, includes settings the current user cannot access (hidden by default)
   */
  "settings/get-all/su": {
    mode: "immediate";
    args: {
    appId: string;
    showRestricted?: boolean };
    response: { settings: Record<string, string> };
  };
  /**
   * Reset a setting for any app (superuser only)
   */
  "settings/reset/su": {
    mode: "immediate";
    args: {
    appId: string;
    key: string;
    schema?: import("./index").SettingsCategory[] };
    response: { success: boolean };
  };
  /**
   * List the settings panels visible to the active user.
   */
  "settings/panels": {
    mode: "immediate";
    args: Record<string, never>;
    response: { panels: import("./index").SettingsPanelSummary[] };
  };
  /**
   * Load one complete authorized panel snapshot.
   */
  "settings/panel": {
    mode: "immediate";
    args: { panelId: string };
    response: import("./index").SettingsPanelResponse;
  };
  /**
   * Invoke one declared panel-private action.
   */
  "settings/action": {
    mode: "immediate";
    args: {
    panelId: string;
    actionId: string;
    invocation?: import("./index").SettingsPanelActionInvocation };
    response: import("./index").SettingsPanelActionResponse;
  };
}

/**
 * UserCommands - Commands for the "user" namespace
 */
export interface UserCommands {
  "user/grant-options": {
    mode: "immediate";
    args: Record<string, never>;
    response: import("./index").UserGrantOptionsResponse;
  };
  /**
   * List all users.
   */
  "user/list": {
    mode: "immediate";
    args: Record<string, never>;
    response: { users: import("./index").UserProfile[] };
  };
  /**
   * Create a new user.
   */
  "user/create": {
    mode: "immediate";
    args: {
    username?: string;
    name: string;
    role?: import("./index").UserRole;
    password: string;
    grants?: string[];
    homeDirectory?: string };
    response: { user: import("./index").UserProfile };
  };
  /**
   * Update user profile details or grants.
   */
  "user/update": {
    mode: "immediate";
    args: {
    username: string;
    name?: string;
    role?: import("./index").UserRole;
    grants?: string[];
    homeDirectory?: string | null };
    response: { user: import("./index").UserProfile };
  };
  /**
   * Delete a user.
   */
  "user/delete": {
    mode: "immediate";
    args: {
    username: string };
    response: { success: boolean };
  };
  /**
   * Set a user's password.
   */
  "user/set-password": {
    mode: "immediate";
    args: {
    username: string;
    password: string };
    response: { success: boolean };
  };
  /**
   * Change the current user's password.
   */
  "user/change-password": {
    mode: "immediate";
    args: {
    currentPassword: string;
    newPassword: string };
    response: { success: boolean; error?: string };
  };
  /**
   * Check whether the current user has a specific grant.
   */
  "user/has-grant": {
    mode: "immediate";
    args: { grant: string };
    response: { allowed: boolean };
  };
  /**
   * Return the configured default username.
   */
  "user/get-default": {
    mode: "immediate";
    args: Record<string, never>;
    response: { username: string | null };
  };
  /**
   * Update the configured default username.
   */
  "user/set-default": {
    mode: "immediate";
    args: {
    username: string | null };
    response: { success: boolean };
  };
}

/**
 * ViewCommands - Commands for the "view" namespace
 */
export interface ViewCommands {
  /**
   * Update bounds for the caller's own view.
   */
  "view/update-bounds": {
    mode: "immediate";
    args: {
    bounds: import("./index").ViewBounds };
    response: { success: boolean };
  };
  /**
   * Update bounds for any app view.
   * Requires "view/manage" permission.
   */
  "view/update-view-bounds": {
    mode: "immediate";
    args: {
    appId: string;
    bounds: import("./index").ViewBounds };
    response: { success: boolean };
  };
  /**
   * Show or hide the caller's own view.
   */
  "view/set-visibility": {
    mode: "immediate";
    args: {
    visible: boolean };
    response: { success: boolean };
  };
  /**
   * Show or hide any app view.
   * Requires "view/manage" permission.
   */
  "view/set-view-visibility": {
    mode: "immediate";
    args: {
    appId: string;
    visible: boolean };
    response: { success: boolean };
  };
  /**
   * Bring caller's own view to the front and focus it.
   */
  "view/focus": {
    mode: "immediate";
    args: { };
    response: { success: boolean };
  };
  /**
   * Bring any app view to the front and focus it.
   * Requires "view/manage" permission.
   */
  "view/focus-view": {
    mode: "immediate";
    args: {
    appId: string };
    response: { success: boolean };
  };
  /**
   * Update the available workspace bounds (e.g. after taskbar resize).
   * Requires "view/manage" permission for app callers.
   */
  "view/update-global-bounds": {
    mode: "immediate";
    args: {
    bounds: import("./index").ViewBounds;
    windowSize: import("./index").WindowSize };
    response: { success: boolean };
  };
  /**
   * Toggle caller's own view between floating and tiled window modes.
   */
  "view/toggle-mode": {
    mode: "immediate";
    args: {
    mode?: "floating" | "tiled" };
    response: { success: boolean };
  };
  /**
   * Toggle any app view between floating and tiled window modes.
   * Requires "view/manage" permission.
   */
  "view/toggle-view-mode": {
    mode: "immediate";
    args: {
    appId: string;
    mode?: "floating" | "tiled" };
    response: { success: boolean };
  };
  /**
   * Get adjacent tiled windows for the caller's app-frame layout controls.
   */
  "view/tile-layout-state": {
    mode: "immediate";
    args: { };
    response: import("./index").TileLayoutState;
  };
  /**
   * Swap the caller with the tiled window on one edge.
   */
  "view/swap-tile": {
    mode: "immediate";
    args: {
    direction: import("./index").TileLayoutDirection };
    response: import("./index").TileLayoutState;
  };
  /**
   * Temporarily cover the tiled window on one edge with the caller.
   */
  "view/expand-tile": {
    mode: "immediate";
    args: {
    direction: import("./index").TileLayoutDirection };
    response: import("./index").TileLayoutState;
  };
  /**
   * Start dragging caller's own view.
   */
  "view/start-drag": {
    mode: "immediate";
    args: {
    startX: number;
    startY: number };
    response: { success: boolean };
  };
  /**
   * End drag operation for caller's own view.
   */
  "view/end-drag": {
    mode: "immediate";
    args: { };
    response: { success: boolean };
  };
  /**
   * Handle global mouse up event to stop any active drag/resize operations.
   * Requires "view/manage" permission for app callers.
   */
  "view/global-mouseup": {
    mode: "immediate";
    args: Record<string, never>;
    response: { success: boolean };
  };
  /**
   * Start resizing caller's own view.
   */
  "view/start-resize": {
    mode: "immediate";
    args: {
    startX: number;
    startY: number;
    direction?: "left" | "right" | "bottom" | "bottom-left" | "bottom-right" };
    response: { success: boolean };
  };
  /**
   * End resize operation for caller's own view.
   */
  "view/end-resize": {
    mode: "immediate";
    args: { };
    response: { success: boolean };
  };
  /**
   * Get the current dimensions of the main window.
   */
  "view/window-size": {
    mode: "immediate";
    args: Record<string, never>;
    response: import("./index").WindowSize;
  };
  /**
   * Set the interface scale (zoom factor) for all views.
   * @param scale - Scale factor as a string (e.g., "1.0" for 100%, "1.5" for 150%)
   */
  "view/set-interface-scale": {
    mode: "immediate";
    args: {
    scale: string };
    response: { success: boolean };
  };
  /**
   * Get the current interface scale.
   */
  "view/get-interface-scale": {
    mode: "immediate";
    args: Record<string, never>;
    response: { scale: number };
  };
}

/**
 * Global command map - merge all command namespaces
 */
export interface CommandMap extends SystemCommands, AssociationsCommands, AppbusCommands, AppearanceCommands, ContextMenuCommands, DaemonCommands, DbCommands, FileCommands, FilePickerCommands, FsCommands, I18nCommands, EventCommands, NotificationCommands, OperationCommands, PackageCommands, ProcessCommands, SessionCommands, SettingsCommands, UserCommands, ViewCommands {}
