/**
 * Command Type Definitions
 *
 * Type-safe command definitions for the Eden IPC system.
 * Commands are organized by namespace (e.g., "app", "view").
 *
 * NOTE: The actual command interfaces are auto-generated from @EdenHandler decorators.
 * See commands.generated.ts (generated by scripts/generate-commands.ts)
 */

/**
 * Re-export auto-generated command interfaces and CommandMap
 * These are generated from @EdenHandler decorators at build time
 */
export * from "./commands.generated";

import { CommandMap } from "./commands.generated";
import type { Operation } from "./Operations";

/**
 * Type-safe command name
 */
export type CommandName = keyof CommandMap;

/**
 * Get command arguments type
 */
export type CommandArgs<T extends CommandName> = CommandMap[T]["args"];

/**
 * Serializable command response before app-side operation controls are attached.
 */
export type CommandResponse<T extends CommandName> = CommandMap[T]["response"];

/** App-facing result: operation commands expose controls bound to their handle. */
export type CommandResult<T extends CommandName> = T extends CommandName
  ? CommandMap[T]["mode"] extends "operation"
    ? Operation<T>
    : CommandResponse<T>
  : never;

/** Eventual completion; immediate commands have no separate completion. */
export type CommandCompletion<T extends CommandName> = CommandMap[T] extends {
  completion: infer R;
}
  ? R
  : never;

/** Reserved stream data; non-stream commands have no chunks. */
export type CommandChunk<T extends CommandName> = CommandMap[T] extends {
  chunk: infer R;
}
  ? R
  : never;
