/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated by scripts/codegen
 * Generated by scripts/codegen
 * Run 'pnpm run codegen' to regenerate.
 */

/**
 * AppearanceEvents - Events for the "appearance" namespace
 */
export interface AppearanceEvents {
  "appearance/wallpaper-changed": import("./index").WallpaperPreset;
}

/**
 * ContextMenuEvents - Events for the "context-menu" namespace
 */
export interface ContextMenuEvents {
  "context-menu/opened": { menu: import("./index").ContextMenuOpenEvent };
  "context-menu/closed": import("./index").ContextMenuResult;
}

/**
 * DaemonEvents - Events for the "daemon" namespace
 */
export interface DaemonEvents {
  "daemon/changed": { status: import("./index").DaemonStatus };
}

/**
 * FileEvents - Events for the "file" namespace
 */
export interface FileEvents {
  "file/opened": { path: string; isDirectory: boolean; appId: string };
}

/**
 * FilePickerEvents - Events for the "file-picker" namespace
 */
export interface FilePickerEvents {
  "file-picker/opened": { picker: import("./index").FilePickerOpenEvent };
  "file-picker/closed": import("./index").FilePickerResult;
}

/**
 * FsEvents - Events for the "fs" namespace
 */
export interface FsEvents {
  "fs/changed": { watchId: string; kind: import("./index").FilesystemChangeKind };
}

/**
 * I18nEvents - Events for the "i18n" namespace
 */
export interface I18nEvents {
  "i18n/locale-changed": { locale: string };
}

/**
 * NotificationEvents - Events for the "notification" namespace
 */
export interface NotificationEvents {
  "notification/added": { notification: import("./index").Notification };
  "notification/removed": { id: string };
  "notification/action-clicked": {
    notificationId: string;
    actionId: string;
  };
}

/**
 * PackageEvents - Events for the "package" namespace
 */
export interface PackageEvents {
  "package/installed": { manifest: import("./index").InstalledPackageManifest };
  "package/uninstalled": | { kind: "app"; packageId: string }
    | { kind: "dlc"; packageId: string; hostAppId: string };
}

/**
 * ProcessEvents - Events for the "process" namespace
 */
export interface ProcessEvents {
  "process/launched": { instance: import("./index").AppInstance };
  "process/stopped": { appId: string };
  "process/reloading": { appId: string };
  "process/error": { appId: string; error: unknown };
  "process/exited": { appId: string; code: number };
}

/**
 * SessionEvents - Events for the "session" namespace
 */
export interface SessionEvents {
  "session/changed": {
    currentUser: import("./index").UserProfile | null;
    previousUsername: string | null;
    reason: "login" | "logout" | "system";
  };
}

/**
 * SettingsEvents - Events for the "settings" namespace
 */
export interface SettingsEvents {
  "settings/changed": { appId: string; key: string; value: string };
  "settings/panels-changed": {
    reason: "catalog" | "grants" | "session" | "state" | "visibility";
  };
}

/**
 * UserEvents - Events for the "user" namespace
 */
export interface UserEvents {
  "user/grant-options-changed": { revision: number };
}

/**
 * ViewEvents - Events for the "view" namespace
 */
export interface ViewEvents {
  "view/view-removed": { viewId: number; appId: string; webContentsId: number };
  "view/bounds-updated": import("./index").ViewBounds;
  "view/interface-scale-changed": { scale: number };
  "view/view-loaded": { viewId: number; appId: string; overlay: boolean };
  "view/view-load-failed": {
    viewId: number;
    appId: string;
    errorCode: number;
    errorDescription: string;
  };
  "view/mode-changed": { mode: "floating" | "tiled"; bounds: import("./index").ViewBounds };
  "view/global-bounds-changed": {
    workspaceBounds: import("./index").ViewBounds;
    windowSize: import("./index").WindowSize;
  };
}

/**
 * Global event map - merge all event namespaces
 */
export interface AppEvents extends AppearanceEvents, ContextMenuEvents, DaemonEvents, FileEvents, FilePickerEvents, FsEvents, I18nEvents, NotificationEvents, PackageEvents, ProcessEvents, SessionEvents, SettingsEvents, UserEvents, ViewEvents {}
