/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated by scripts/generate-commands.ts
 * Run 'pnpm run codegen' to regenerate.
 */

/**
 * AppearanceEvents - Events for the "appearance" namespace
 */
export interface AppearanceEvents {
  "appearance/wallpaper-changed": import("./index").WallpaperPreset;
}

/**
 * FileEvents - Events for the "file" namespace
 */
export interface FileEvents {
  "file/opened": { path: string; isDirectory: boolean; appId: string };
}

/**
 * I18nEvents - Events for the "i18n" namespace
 */
export interface I18nEvents {
  "i18n/locale-changed": { locale: string };
}

/**
 * NotificationEvents - Events for the "notification" namespace
 */
export interface NotificationEvents {
  "notification/added": { notification: import("./index").Notification };
  "notification/removed": { id: string };
}

/**
 * PackageEvents - Events for the "package" namespace
 */
export interface PackageEvents {
  "package/installed": { manifest: import("./index").AppManifest };
  "package/uninstalled": { appId: string };
}

/**
 * ProcessEvents - Events for the "process" namespace
 */
export interface ProcessEvents {
  "process/launched": { instance: import("./index").AppInstance };
  "process/stopped": { appId: string };
  "process/error": { appId: string; error: any };
  "process/exited": { appId: string; code: number };
}

/**
 * SettingsEvents - Events for the "settings" namespace
 */
export interface SettingsEvents {
  "settings/changed": { appId: string; key: string; value: string };
}

/**
 * ViewEvents - Events for the "view" namespace
 */
export interface ViewEvents {
  "view/bounds-updated": import("./index").ViewBounds;
  "view/global-bounds-changed": {
    workspaceBounds: import("./index").ViewBounds;
    windowSize: import("./index").WindowSize;
  };
  "view/view-loaded": { viewId: number; appId: string; overlay: boolean };
  "view/view-load-failed": {
    viewId: number;
    appId: string;
    errorCode: number;
    errorDescription: string;
  };
  "view/mode-changed": { mode: "floating" | "tiled"; bounds: import("./index").ViewBounds };
}

/**
 * Global event map - merge all event namespaces
 */
export interface AppEvents extends AppearanceEvents, FileEvents, I18nEvents, NotificationEvents, PackageEvents, ProcessEvents, SettingsEvents, ViewEvents {}
