/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file contains typed Eden grants derived from EDEN_SETTINGS_SCHEMA.
 * Generated by scripts/codegen
 * Run 'pnpm run codegen' to regenerate.
 */

/** Eden's app ID for settings namespace */
export declare const EDEN_APP_ID = "com.eden";

/**
 * Eden Grants Registry
 *
 * Typed grants derived from EDEN_SETTINGS_SCHEMA.
 * Each category with a `permission` field becomes a grant entry.
 */
export declare const EdenGrants: {
  /** Grant for appearance settings (settings/com.eden/appearance) */
  readonly APPEARANCE: "settings/com.eden/appearance";
  /** Grant for users settings (settings/com.eden/users) */
  readonly USERS: "settings/com.eden/users";
  /** Grant for apps settings (settings/com.eden/apps/manage) */
  readonly APPS: "settings/com.eden/apps/manage";
};

/** Type for valid Eden grant values */
export type EdenGrant = (typeof EdenGrants)[keyof typeof EdenGrants];
