/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * Type declarations for runtime arrays.
 * Generated by scripts/generate-commands.ts
 * Run 'pnpm run codegen' to regenerate.
 */

// Command names array
export declare const COMMAND_NAMES: readonly string[];

// Event names array
export declare const APP_EVENT_NAMES: readonly string[];
