packages:
  - packages/*
  - genesis
  - packages/sdk/apps/**/*

catalog:
  '@solidjs/testing-library': ^0.8.10
  '@types/jest': ^30.0.0
  '@types/node': ^26.1.2
  commander: ^14.0.3
  concurrently: ^10.0.4
  electron: ^43.2.0
  jest: ^30.4.2
  jsdom: ^30.0.1
  solid-icons: ^1.2.0
  solid-js: ^1.9.14
  ts-jest: ^29.4.12
  ts-node: ^10.9.2
  typescript: ^6.0.3
  vite: ^7.3.6
  vite-plugin-solid: ^2.11.14
  vitest: ^4.1.10

allowBuilds:
  electron: true
  esbuild: true
  lightningcss-cli: true
  simple-git-hooks: true
  sqlite3: true
  unrs-resolver: true

onlyBuiltDependencies:
  - electron
  - esbuild
  - lightningcss-cli
  - sqlite3
