packages:
  - packages/*
  - genesis
  - packages/sdk/apps/**/*

allowBuilds:
  electron: true
  esbuild: true
  lightningcss-cli: true
  simple-git-hooks: true
  sqlite3: true

onlyBuiltDependencies:
  - electron
  - esbuild
  - lightningcss-cli
  - sqlite3
