packages:
  - packages/*
  - genesis
  - packages/sdk/apps/**/*
  - packages/sdk/dlcs/**/*

catalog:
  '@solidjs/testing-library': ^0.8.10
  '@types/jest': ^30.0.0
  '@types/node': ^26.6.2
  commander: ^15.0.0
  concurrently: ^10.0.5
  electron: ^44.4.5
  jest: ^30.5.2
  jsdom: ^30.1.1
  semver: ^7.7.3
  solid-icons: ^1.2.0
  solid-js: ^1.9.15
  ts-jest: ^29.4.12
  ts-node: ^10.9.2
  typescript: ^7.0.2
  vite: ^8.3.0
  vite-plugin-solid: ^2.11.14
  vitest: ^5.0.1

allowBuilds:
  electron: true
  esbuild: true
  lightningcss-cli: true
  simple-git-hooks: true
  sqlite3: true
  unrs-resolver: true

onlyBuiltDependencies:
  - electron
  - esbuild
  - lightningcss-cli
  - sqlite3
