/**
 * Command Type Definitions
 *
 * Type-safe command definitions for the Eden IPC system.
 * Commands are organized by namespace (e.g., "app", "view").
 * 
 * NOTE: The actual command interfaces are auto-generated from @CommandHandler decorators.
 * See commands.generated.ts (generated by scripts/generate-commands.ts)
 */

import { ViewBounds } from "./index";

/**
 * Re-export auto-generated command interfaces
 * These are generated from @CommandHandler decorators at build time
 */
import { AppCommands } from "./commands.generated";
export { AppCommands };

/**
 * View-related commands (namespace: "view")
 * Reserved for future use when commands are moved to ViewManager
 */
export interface ViewCommands {
  // Empty for now - commands will be moved here when ViewManager is created
}

/**
 * Global command map - merge all command namespaces
 */
export interface CommandMap extends AppCommands, ViewCommands {}

/**
 * Type-safe command name
 */
export type CommandName = keyof CommandMap;

/**
 * Get command arguments type
 */
export type CommandArgs<T extends CommandName> = CommandMap[T];

/**
 * Get command result type (for now all commands return any)
 */
export type CommandResult<T extends CommandName = CommandName> = any;

