/**
 * Command Type Definitions
 *
 * Type-safe command definitions for the Eden IPC system.
 * Commands are organized by namespace (e.g., "app", "view").
 * 
 * NOTE: The actual command interfaces are auto-generated from @CommandHandler decorators.
 * See commands.generated.ts (generated by scripts/generate-commands.ts)
 */

/**
 * Re-export auto-generated command interfaces and CommandMap
 * These are generated from @CommandHandler decorators at build time
 */
export * from "./commands.generated";

import { CommandMap } from "./commands.generated";

/**
 * Type-safe command name
 */
export type CommandName = keyof CommandMap;

/**
 * Get command arguments type
 */
export type CommandArgs<T extends CommandName> = CommandMap[T];

/**
 * Get command result type (for now all commands return any)
 */
export type CommandResult<T extends CommandName = CommandName> = any;

