/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated by scripts/generate-commands.ts
 * Run 'npm run codegen' to regenerate.
 */

/**
 * SystemCommands - Commands for the "system" namespace
 */
export interface SystemCommands {
  /**
   * Get system information including platform, versions, and running apps.
   */
  "system/info": {
    args: Record<string, never>;
    response: SystemInfo;
  };
}

/**
 * FileCommands - Commands for the "file" namespace
 */
export interface FileCommands {
  /**
   * Open a file with its default handler
   */
  "file/open": {
    args: { path: string };
    response: FileOpenResult;
  };
  /**
   * Open a file with a specific app
   */
  "file/open-with": {
    args: { path: string; appId: string };
    response: FileOpenResult;
  };
  /**
   * Get the default handler app for a file extension
   */
  "file/get-handler": {
    args: { extension: string };
    response: { appId: string | undefined };
  };
  /**
   * Set user preference for a file extension's default handler
   */
  "file/set-default-handler": {
    args: { extension: string; appId: string };
    response: void;
  };
  /**
   * Remove user preference for a file extension (revert to default)
   */
  "file/remove-default-handler": {
    args: { extension: string };
    response: void;
  };
  /**
   * Get all apps that can handle a specific file extension
   */
  "file/get-supported-handlers": {
    args: { extension: string };
    response: FileHandlerInfo[];
  };
  /**
   * Get all file type associations
   */
  "file/get-associations": {
    args: Record<string, never>;
    response: Record<string, { default: string | undefined; userOverride: string | undefined }>;
  };
}

/**
 * FsCommands - Commands for the "fs" namespace
 */
export interface FsCommands {
  /**
   * Read the contents of a file.
   */
  "fs/read": {
    args: {
    path: string;
    encoding?: BufferEncoding;
  };
    response: string;
  };
  /**
   * Write content to a file, creating directories if needed.
   */
  "fs/write": {
    args: {
    path: string;
    content: string;
    encoding?: BufferEncoding;
  };
    response: void;
  };
  /**
   * Check if a file or directory exists.
   */
  "fs/exists": {
    args: { path: string };
    response: boolean;
  };
  /**
   * Create a directory and any necessary parent directories.
   */
  "fs/mkdir": {
    args: { path: string };
    response: void;
  };
  /**
   * List contents of a directory.
   */
  "fs/readdir": {
    args: { path: string };
    response: string[];
  };
  /**
   * Get file or directory statistics.
   */
  "fs/stat": {
    args: { path: string };
    response: FileStats;
  };
  /**
   * Search for files and directories using glob patterns.
   */
  "fs/search": {
    args: {
    path: string;
    pattern: string;
    limit?: number;
  };
    response: SearchResult[];
  };
  /**
   * Delete a file or directory.
   * For directories, removes recursively.
   */
  "fs/delete": {
    args: { path: string };
    response: void;
  };
}

/**
 * PackageCommands - Commands for the "package" namespace
 */
export interface PackageCommands {
  /**
   * Install an application from a local path.
   */
  "package/install": {
    args: { sourcePath: string };
    response: AppManifest;
  };
  /**
   * Uninstall an application by its ID.
   */
  "package/uninstall": {
    args: { appId: string };
    response: boolean;
  };
  /**
   * List all installed applications.
   * @param showHidden - If true, includes overlay apps (hidden by default)
   */
  "package/list": {
    args: { showHidden?: boolean };
    response: AppManifest[];
  };
  /**
   * Toggle hot reload for an app
   */
  "package/toggle-hot-reload": {
    args: {
    appId: string;
  };
    response: { enabled: boolean };
  };
  /**
   * Check if hot reload is enabled for an app
   */
  "package/is-hot-reload-enabled": {
    args: {
    appId: string;
  };
    response: { enabled: boolean };
  };
  /**
   * Get the icon for an installed application as a data URL.
   */
  "package/get-icon": {
    args: {
    appId: string;
  };
    response: { icon: string | undefined };
  };
}

/**
 * ProcessCommands - Commands for the "process" namespace
 */
export interface ProcessCommands {
  /**
   * Launch an application instance.
   */
  "process/launch": {
    args: {
    appId: string;
    bounds?: ViewBounds;
  };
    response: LaunchResult;
  };
  /**
   * Stop a running application instance.
   */
  "process/stop": {
    args: { appId: string };
    response: { success: boolean };
  };
  /**
   * List all running application processes.
   * @param showHidden - If true, includes overlay apps (hidden by default)
   */
  "process/list": {
    args: { showHidden?: boolean };
    response: AppInstance[];
  };
}

/**
 * ViewCommands - Commands for the "view" namespace
 */
export interface ViewCommands {
  /**
   * Update the bounds (position and size) of a specific view.
   */
  "view/update-view-bounds": {
    args: {
    appId: string;
    bounds: ViewBounds;
  };
    response: { success: boolean };
  };
  /**
   * Show or hide a specific view.
   */
  "view/set-view-visibility": {
    args: {
    appId: string;
    visible: boolean;
  };
    response: { success: boolean };
  };
  /**
   * Bring an application's view to the front and focus it.
   */
  "view/focus-app": {
    args: { appId: string };
    response: { success: boolean };
  };
  /**
   * Update the available workspace bounds (e.g. after taskbar resize).
   */
  "view/update-global-bounds": {
    args: {
    bounds: ViewBounds;
    windowSize: WindowSize;
  };
    response: { success: boolean };
  };
  /**
   * Toggle between floating and tiled window modes.
   */
  "view/toggle-view-mode": {
    args: {
    appId: string;
    mode?: "floating" | "tiled";
  };
    response: { success: boolean };
  };
  /**
   * Start dragging a window.
   */
  "view/start-drag": {
    args: {
    appId: string;
    startX: number;
    startY: number;
  };
    response: { success: boolean };
  };
  /**
   * End the current drag operation.
   */
  "view/end-drag": {
    args: { appId: string };
    response: { success: boolean };
  };
  /**
   * Handle global mouse up event to stop any active drag/resize operations.
   */
  "view/global-mouseup": {
    args: Record<string, never>;
    response: { success: boolean };
  };
  /**
   * Start resizing a window.
   */
  "view/start-resize": {
    args: {
    appId: string;
    startX: number;
    startY: number;
  };
    response: { success: boolean };
  };
  /**
   * End the current resize operation.
   */
  "view/end-resize": {
    args: {
    appId: string;
  };
    response: { success: boolean };
  };
  /**
   * Get the current dimensions of the main window.
   */
  "view/window-size": {
    args: Record<string, never>;
    response: WindowSize;
  };
}

/**
 * Global command map - merge all command namespaces
 */
export interface CommandMap extends SystemCommands, FileCommands, FsCommands, PackageCommands, ProcessCommands, ViewCommands {}
