/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated by scripts/generate-commands.ts
 * Run 'npm run codegen' to regenerate.
 */

/**
 * SystemCommands - Commands for the "system" namespace
 */
export interface SystemCommands {
  "system/info": Record<string, never>;
  "system/window-size": Record<string, never>;
}

/**
 * PackageCommands - Commands for the "package" namespace
 */
export interface PackageCommands {
  "package/install": { sourcePath: string };
  "package/uninstall": { appId: string };
  "package/list-installed": Record<string, never>;
}

/**
 * ProcessCommands - Commands for the "process" namespace
 */
export interface ProcessCommands {
  "process/launch": { appId: string; bounds?: import("./index").ViewBounds };
  "process/stop": { appId: string };
  "process/list": Record<string, never>;
}

/**
 * ViewCommands - Commands for the "view" namespace
 */
export interface ViewCommands {
  "view/update-view-bounds": { appId: string; bounds: import("./index").ViewBounds };
  "view/set-view-visibility": { appId: string; visible: boolean };
  "view/focus-app": { appId: string };
  "view/update-workspace-bounds": { bounds: import("./index").ViewBounds };
  "view/toggle-view-mode": { appId: string; mode?: "floating" | "tiled" };
  "view/start-drag": { appId: string; startX: number; startY: number };
  "view/end-drag": { appId: string };
  "view/global-mouseup": Record<string, never>;
  "view/start-resize": { appId: string; startX: number; startY: number };
  "view/end-resize": { appId: string };
}

/**
 * Global command map - merge all command namespaces
 */
export interface CommandMap extends SystemCommands, PackageCommands, ProcessCommands, ViewCommands {}

/**
 * Array of all available command names
 */
export const COMMAND_NAMES = [
  "system/info",
  "system/window-size",
  "package/install",
  "package/uninstall",
  "package/list-installed",
  "process/launch",
  "process/stop",
  "process/list",
  "view/update-view-bounds",
  "view/set-view-visibility",
  "view/focus-app",
  "view/update-workspace-bounds",
  "view/toggle-view-mode",
  "view/start-drag",
  "view/end-drag",
  "view/global-mouseup",
  "view/start-resize",
  "view/end-resize"
] as const;
