/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated by scripts/generate-commands.ts
 * Run 'pnpm run codegen' to regenerate.
 */

/**
 * FileEvents - Events for the "file" namespace
 */
export interface FileEvents {
  "file/opened": { path: string; isDirectory: boolean; appId: string };
}

/**
 * PackageEvents - Events for the "package" namespace
 */
export interface PackageEvents {
  "package/installed": { manifest: import("./index").AppManifest };
  "package/uninstalled": { appId: string };
}

/**
 * ProcessEvents - Events for the "process" namespace
 */
export interface ProcessEvents {
  "process/launched": { instance: import("./index").AppInstance };
  "process/stopped": { appId: string };
  "process/error": { appId: string; error: any };
  "process/exited": { appId: string; code: number };
}

/**
 * ViewEvents - Events for the "view" namespace
 */
export interface ViewEvents {
  "view/bounds-updated": import("./index").ViewBounds;
  "view/global-bounds-changed": { workspaceBounds: import("./index").ViewBounds; windowSize: import("./index").WindowSize };
}

/**
 * Global event map - merge all event namespaces
 */
export interface AppEvents extends FileEvents, PackageEvents, ProcessEvents, ViewEvents {}
