/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated by scripts/generate-commands.ts
 * Run 'pnpm run codegen' to regenerate.
 */

/**
 * PackageEvents - Events for the "package" namespace
 */
export interface PackageEvents {
  "package/installed": { manifest: AppManifest };
  "package/uninstalled": { appId: string };
}

/**
 * ProcessEvents - Events for the "process" namespace
 */
export interface ProcessEvents {
  "process/launched": { instance: AppInstance };
  "process/stopped": { appId: string };
  "process/error": { appId: string; error: any };
  "process/exited": { appId: string; code: number };
}

/**
 * ViewEvents - Events for the "view" namespace
 */
export interface ViewEvents {
  "view/bounds-updated": ViewBounds;
  "view/global-bounds-changed": { workspaceBounds: ViewBounds; windowSize: WindowSize };
}

/**
 * Global event map - merge all event namespaces
 */
export interface AppEvents extends PackageEvents, ProcessEvents, ViewEvents {}
