/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated by scripts/generate-commands.ts
 * Run 'npm run codegen' to regenerate.
 */

/**
 * PackageEvents - Events for the "package" namespace
 */
export interface PackageEvents {
  "package/installed": { manifest: import("./index").AppManifest };
  "package/uninstalled": { appId: string };
}

/**
 * ProcessEvents - Events for the "process" namespace
 */
export interface ProcessEvents {
  "process/launched": { instance: import("./index").AppInstance };
  "process/stopped": { appId: string };
  "process/error": { appId: string; error: any };
  "process/exited": { appId: string; code: number };
}

/**
 * ViewEvents - Events for the "view" namespace
 */
export interface ViewEvents {
  "view/bounds-updated": import("./index").ViewBounds;
  "view/workspace-bounds-changed": { bounds: import("./index").ViewBounds };
}

/**
 * Global event map - merge all event namespaces
 */
export interface AppEvents extends PackageEvents, ProcessEvents, ViewEvents {}

/**
 * Array of all available event names
 */
export const APP_EVENT_NAMES = [
  "package/installed",
  "package/uninstalled",
  "process/launched",
  "process/stopped",
  "process/error",
  "process/exited",
  "view/bounds-updated",
  "view/workspace-bounds-changed"
] as const;
