/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file contains runtime arrays for command and event names.
 * Generated by scripts/generate-commands.ts
 * Run 'pnpm run codegen' to regenerate.
 */

// Command names array
export const COMMAND_NAMES = [
  "system/info",
  "fs/read",
  "fs/write",
  "fs/exists",
  "fs/mkdir",
  "fs/readdir",
  "fs/stat",
  "fs/search",
  "fs/delete",
  "package/install",
  "package/uninstall",
  "package/list-installed",
  "package/toggle-hot-reload",
  "package/is-hot-reload-enabled",
  "process/launch",
  "process/stop",
  "process/list",
  "view/update-view-bounds",
  "view/set-view-visibility",
  "view/focus-app",
  "view/update-global-bounds",
  "view/toggle-view-mode",
  "view/start-drag",
  "view/end-drag",
  "view/global-mouseup",
  "view/start-resize",
  "view/end-resize",
  "view/window-size",
] as const;

// Event names array
export const APP_EVENT_NAMES = [
  "package/installed",
  "package/uninstalled",
  "process/launched",
  "process/stopped",
  "process/error",
  "process/exited",
  "view/bounds-updated",
  "view/global-bounds-changed",
] as const;
