/**
 * Shared utilities for codegen
 */

import { Node } from "ts-morph";

/**
 * Replace custom type references with inline imports
 */
export function replaceTypesWithInlineImports(
  typeExpression: string,
  exportedTypes: Set<string>,
): string {
  // Replace custom types with inline imports
  // Match capitalized identifiers that look like type names
  return typeExpression.replace(/\b([A-Z][a-zA-Z0-9]*)\b/g, (match) => {
    if (exportedTypes.has(match)) {
      return `import("./index").${match}`; // Replace with inline import
    }
    return match; // Keep as-is (built-in or local)
  });
}

/**
 * Extract JSDoc comments from a node
 */
export function extractDocs(node: Node): string[] {
  if (Node.isJSDocable(node)) {
    return node.getJsDocs().map((doc) => doc.getInnerText());
  }
  return [];
}

/**
 * Generate auto-generated file header
 */
export function generateHeader(description: string): string[] {
  return [
    "/**",
    " * AUTO-GENERATED FILE - DO NOT EDIT",
    " *",
    ` * ${description}`,
    " * Generated by scripts/codegen",
    " * Run 'pnpm run codegen' to regenerate.",
    " */",
    "",
  ];
}

/**
 * Convert namespace to PascalCase interface name
 */
export function namespaceToInterfaceName(
  namespace: string,
  suffix: string,
): string {
  return (
    namespace
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("") + suffix
  );
}
